In [13]:
import pandas as pd
import numpy as np
data=pd.read_csv("iris.csv")

In [14]:
print(data)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]


In [16]:
x = data.iloc[:,:-1].values
print(x)
y = data.iloc[:,-1]

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [8]:
# encoding the category
from sklearn.preprocessing import LabelEncoder
y = LabelEncoder().fit_transform(y)
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [20]:
#split train and test data
from sklearn.model_selection import train_test_split
x_train, x_test , y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=3)
print(x_train)
print(y_train)

[[5.8 4.  1.2 0.2]
 [4.8 3.4 1.9 0.2]
 [6.9 3.1 5.4 2.1]
 [6.6 2.9 4.6 1.3]
 [4.4 2.9 1.4 0.2]
 [5.2 3.5 1.5 0.2]
 [6.7 3.  5.  1.7]
 [4.5 2.3 1.3 0.3]
 [6.4 2.7 5.3 1.9]
 [6.2 2.2 4.5 1.5]
 [6.4 2.8 5.6 2.1]
 [5.8 2.7 3.9 1.2]
 [4.6 3.6 1.  0.2]
 [5.1 3.5 1.4 0.3]
 [6.1 3.  4.9 1.8]
 [6.4 3.2 4.5 1.5]
 [5.1 3.3 1.7 0.5]
 [6.  2.7 5.1 1.6]
 [5.8 2.7 5.1 1.9]
 [5.4 3.  4.5 1.5]
 [4.8 3.  1.4 0.3]
 [5.  3.2 1.2 0.2]
 [5.8 2.7 5.1 1.9]
 [7.  3.2 4.7 1.4]
 [6.1 2.8 4.7 1.2]
 [4.9 3.1 1.5 0.1]
 [6.3 3.4 5.6 2.4]
 [5.1 3.8 1.5 0.3]
 [6.5 3.  5.5 1.8]
 [5.7 2.9 4.2 1.3]
 [5.  3.6 1.4 0.2]
 [4.8 3.  1.4 0.1]
 [6.8 3.2 5.9 2.3]
 [5.9 3.2 4.8 1.8]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [5.1 2.5 3.  1.1]
 [6.4 3.1 5.5 1.8]
 [6.3 3.3 6.  2.5]
 [4.9 3.1 1.5 0.1]
 [6.7 3.3 5.7 2.1]
 [5.7 3.  4.2 1.2]
 [4.7 3.2 1.6 0.2]
 [5.1 3.4 1.5 0.2]
 [7.4 2.8 6.1 1.9]
 [7.7 3.8 6.7 2.2]
 [5.8 2.8 5.1 2.4]
 [5.7 2.8 4.1 1.3]
 [5.2 2.7 3.9 1.4]
 [6.3 2.3 4.4 1.3]
 [5.1 3.8 1.9 0.4]
 [5.5 3.5 1.3 0.2]
 [6.4 3.2 5.

In [21]:
# Train the model 
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train,y_train)

GaussianNB()

In [22]:
#Prediction usinf naive Bayes
y_predict = gnb.predict(x_test)
print('Predicted value by model ', y_predict)
print('Actual value in dataset ', y_test)

Predicted value by model  ['setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'virginica' 'versicolor'
 'setosa' 'virginica' 'versicolor' 'versicolor' 'setosa' 'versicolor'
 'versicolor' 'virginica' 'setosa' 'versicolor' 'virginica' 'virginica'
 'setosa' 'virginica' 'virginica' 'virginica' 'versicolor' 'setosa'
 'virginica' 'versicolor' 'versicolor' 'versicolor' 'versicolor']
Actual value in dataset  47         setosa
3          setosa
31         setosa
25         setosa
15         setosa
118     virginica
89     versicolor
6          setosa
103     virginica
65     versicolor
88     versicolor
38         setosa
92     versicolor
53     versicolor
140     virginica
40         setosa
72     versicolor
135     virginica
113     virginica
42         setosa
126     virginica
112     virginica
141     virginica
76     versicolor
5          setosa
109     virginica
134     virginica
67     versicolor
57     versicolor
86     versicolor
Name: species, dtype: object


In [23]:
# confusion matrix
from sklearn.metrics import confusion_matrix
confusion_mat = confusion_matrix(y_test, y_predict)

print('confusion matrix \n', confusion_mat)

confusion matrix 
 [[10  0  0]
 [ 0 10  0]
 [ 0  1  9]]


In [24]:
# classifier accuracy 
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,y_predict)
print('Accuracy ', accuracy)

Accuracy  0.9666666666666667


In [29]:
new_input = np.array([[5.1, 3.5, 1.4, 0.2]])  # Example new input
predicted_class = gnb.predict(new_input)
print('Predicted class for new input:', predicted_class)


Predicted class for new input: ['setosa']
